### ISSUE TITLE
dlopen failed: library "/data/data/myApp/lib/librsa_bridge.so" not found

### ISSUE THREAD

**Issue by dev-whoan** [jerson/flutter-rsa#25]
Hello, I'm having trouble with using fast_rsa.

I'm testing it on Android API 31, and the code is:

```
void generateRSAKeyPair() async {
  var result = await RSA.generate(2048);   //here
  log(result.publicKey);
  log(result.privateKey);
}
```

And the error is :
```
I/flutter ( 9440): fallback to open DynamicLibrary on older devices
E/flutter ( 9440): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library '/data/data/myApp/lib/librsa_bridge.so': dlopen failed: library "/data/data/myApp/lib/librsa_bridge.so" not found
E/flutter ( 9440): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
E/flutter ( 9440): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
E/flutter ( 9440): #2      Binding.openLib (package:fast_rsa/bridge/binding.dart:139:33)
E/flutter ( 9440): #3      new Binding._internal (package:fast_rsa/bridge/binding.dart:25:16)
E/flutter ( 9440): #4      Binding._singleton (package:fast_rsa/bridge/binding.dart:16:45)
E/flutter ( 9440): #5      Binding._singleton (package:fast_rsa/bridge/binding.dart)
E/flutter ( 9440): #6      new Binding (package:fast_rsa/bridge/binding.dart:21:12)
E/flutter ( 9440): #7      RSA.bindingEnabled (package:fast_rsa/fast_rsa.dart:38:32)
E/flutter ( 9440): #8      RSA.bindingEnabled (package:fast_rsa/fast_rsa.dart)
E/flutter ( 9440): #9      RSA._call (package:fast_rsa/fast_rsa.dart:41:9)
E/flutter ( 9440): #10     RSA._keyPairResponse (package:fast_rsa/fast_rsa.dart:77:22)
E/flutter ( 9440): #11     RSA.generate (package:fast_rsa/fast_rsa.dart:435:18)
```

And the dependency:
```

dependencies:
  flutter:
    sdk: flutter
  http: 0.13.4
  json_annotation: ^4.4.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  rsa_encrypt: ^2.0.0
  path_provider: ^2.0.7
  encrypt: ^5.0.1
  fast_rsa: ^3.1.0
```

Can I get some help?

Thanks.
